fix: Adapt code to the new operator-sdk.
redhat-developer/codeready-workspaces-operator pull request #50
Opened 2021-07-26 15:30 UTC by AndrienkoAleksandr

### What does this PR do?
Adapt code to the new operator-sdk.

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1956

#### Release Notes

#### Docs PR (if applicable)

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

2021-07-26 16:04 UTC, nickboldt commented on build/scripts/sync-che-olm-to-crw-olm.sh
> +# simple copy - old way CRW 2.8
we can remove these lines entirely, 2.8 is dead as of 2.11 code base.

2021-07-26 16:04 UTC, nickboldt commented on build/scripts/sync-che-olm-to-crw-olm.sh
> +cp "${TARGETDIR}/bundle/${OLM_CHANNEL}/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml" "${TARGETDIR}/manifests/codeready-workspaces.crd.yaml"
so we apply the yaml changes to `CR_YAML` = `config/samples/org.eclipse.che_v1_checluster.yaml`, but then you copy  unchanged file `eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml` to /manifests/ folder?

2021-07-26 16:05 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> -# delete unneeded files
does this mean we'll be committing all the k8s specfic files into downstream where they'll never be used/needed?

2021-07-26 16:06 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +		-e 's|"eclipse/che-operator:[0-9.]+": *"che-operator:[0-9.]+"|"'${CRW_RRIO}'/server-operator-rhel8:2.0": "server-operator-rhel8:2.0"|' \
can we add the `quay.io` in upstream che-operator code, so that there's no ambiguity about where the operator container is published?

2021-07-26 16:07 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +		-e 's|"eclipse/che-operator:[0-9.]+": *"che-operator:[0-9.]+"|"'${CRW_RRIO}'/server-operator-rhel8:2.0": "server-operator-rhel8:2.0"|' \
also note this change is for the old CRW 2.0 name of the operator container. We might be able to remove this change entirely, if you're no longer running tests based on Che 7.3

2021-07-26 16:08 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +
unneeded space

2021-07-26 16:09 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +CR_YAML="config/samples/org.eclipse.che_v1_checluster.yaml"
should this be line 259, right above the `changed=...` line?

2021-07-26 16:10 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +yq -yY '.spec.template.spec.containers[1].env |= sort_by(.name)' "${TARGETDIR}/${OPERATOR_DEPLOYMENT_YAML}2" > "${TARGETDIR}/${OPERATOR_DEPLOYMENT_YAML}"
you could do this sorting in upstream too, so that the env vars are alphabetically ordered. Makes the file cleaner and diffs easier to see.

2021-07-26 16:11 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +# todo remove extra files from pkd/deploy
is there a followup JIRA or GH issue for these TODOs?

2021-07-26 16:12 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +
don't hard code 2.11 here. Needs to be a variable `${CRW_VERSION}`

2021-07-26 16:12 UTC, nickboldt requested changes
some changes needed.

2021-07-26 18:45 UTC, AndrienkoAleksandr commented on build/scripts/sync-che-olm-to-crw-olm.sh
> +	source "${SCRIPTS_DIR}/insert-related-images-to-csv.sh" -v "${CSV_VERSION}" -t "${TARGETDIR}" --crw-branch "${MIDSTM_BRANCH}"
I will remove this change. I applied it only to debug script using bash debugger from VSCode.

2021-07-26 19:01 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> -# delete unneeded files
yeah, and I saw you're deleting stuff lower down in this script too, so +1, all good.

2021-07-27 13:19 UTC, AndrienkoAleksandr commented on build/scripts/sync-che-olm-to-crw-olm.sh
> +cp "${TARGETDIR}/bundle/${OLM_CHANNEL}/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml" "${TARGETDIR}/manifests/codeready-workspaces.crd.yaml"
CR_YAML - that's a custom resource file. org_v1_che_crd.yaml - custom resource definitions for CR_YAML.

2021-07-27 13:24 UTC, AndrienkoAleksandr commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +
Ok, but I reworked tests in a way when we don't need patch test file controllers/che/checluster_controller_test.go. So I will remove this change.

2021-07-27 17:37 UTC, nickboldt commented on build/scripts/sync-che-olm-to-crw-olm.sh
> +cp "${TARGETDIR}/bundle/${OLM_CHANNEL}/eclipse-che-preview-openshift/manifests/org_v1_che_crd.yaml" "${TARGETDIR}/manifests/codeready-workspaces.crd.yaml"
ok, just checking that this is correct since it's different from CRW 2.10

2021-07-27 17:39 UTC, nickboldt commented on .vscode/launch.json
> +        "name": "Bash-Debug sync che-operator",
since these scripts should generally be run in order (operator then olm) should they be numbered, like in lots of other devfiles in CRW? https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-devfileregistry/devfiles/00_java11-maven-microprofile-bootable/devfile.yaml#L47-L61 for example

2021-07-27 17:39 UTC, nickboldt commented on .vscode/launch.json
> +          "2.11.0",
hard coded version again. Please make sure this file is being generated via the sync script if you're going to require a version in here.

2021-07-27 17:40 UTC, nickboldt commented on .vscode/launch.json
> +          "2.11.0",
hard coded version - can this be generated from https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/VERSION or something?

2021-07-27 17:40 UTC, nickboldt commented on .vscode/launch.json
> +          "2.10.0",
hardcoded value will need updating.

2021-07-27 17:42 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +cp -f "${SOURCEDIR}/main.go" "${TARGETDIR}/main.go"
this could be one line 
```
cp -f "${SOURCEDIR}/main.go" "${SOURCEDIR}/go.mod" "${SOURCEDIR}/go.sum" "${TARGETDIR}/"
```

2021-07-27 17:42 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +rm -rf "${TARGETDIR}/pkg/deploy/server/deployment_che.go"
please reduce this to one line

2021-07-27 17:43 UTC, nickboldt commented on build/scripts/sync-che-operator-to-crw-operator.sh
> +# Comment not used images
"Comment out unused images"

2021-07-27 17:46 UTC, nickboldt approved these changes
overall good, but your launch.json will break when we move to 2.12 unless it's manually updated. 

Some other style nitpicks around multiple lines vs. joined lines are your call.

2021-07-28 06:09 UTC, AndrienkoAleksandr commented on .vscode/launch.json
> +          "2.11.0",
I guess we could do that using pre-launch task. This task should retrieve information before debug and store using env file. But looks like bash debugger doesn't support env files. So I removed launch.json....

2021-07-28 09:14 UTC, merged